{ pkgs, lib, config ? {} }:

#
# SECURITY PACK (PARAMETERIZED)
#
# This pack materializes a SECURITY.md file documenting security policies and reporting.
# When enabled, all repositories receive this security policy.
#
# CONFIGURATION:
# This pack can be customized via .nixline.toml configuration:
#
# [organization]
# security_email = "security@mycompany.com"
#
# [packs.security]
# response_time = "within 24 hours"
# disclosure_policy = "coordinated"
# supported_versions = [
#   { version = "2.x.x", supported = true },
#   { version = "1.x.x", supported = false }
# ]
#
# ENVIRONMENT VARIABLES:
# Can also be customized via environment variables from enhanced sync app:
# - NIXLINE_ORG_EMAIL: Security contact email
#

let
  # Organization configuration with fallbacks
  orgEmail =
    if builtins.getEnv "NIXLINE_ORG_EMAIL" != "" then builtins.getEnv "NIXLINE_ORG_EMAIL"
    else config.organization.security_email or "security@example.com";

  # Pack-specific configuration with defaults
  packConfig = config.packs.security or {};

  # Security policy configuration
  responseTime = packConfig.response_time or "promptly";
  disclosurePolicy = packConfig.disclosure_policy or "coordinated";

  # Default supported versions
  defaultVersions = [
    { version = "1.x.x"; supported = true; }
    { version = "< 1.0"; supported = false; }
  ];

  supportedVersions = packConfig.supported_versions or defaultVersions;

  # Generate version table
  versionTable = lib.concatStringsSep "\n" (map (v:
    "| ${v.version} | ${if v.supported then ":white_check_mark:" else ":x:"} |"
  ) supportedVersions);

  # Generate disclosure policy section
  disclosurePolicyText =
    if disclosurePolicy == "coordinated" then ''
      ## Disclosure Policy

      We follow a coordinated disclosure policy. When we receive a security bug report, we will:

      1. Confirm the problem and determine affected versions
      2. Audit code to find similar problems
      3. Prepare fixes for all supported releases
      4. Coordinate with the reporter on disclosure timeline
      5. Release patches and public disclosure simultaneously

      We typically aim for a 90-day disclosure timeline, but this may be adjusted based on the complexity of the issue.
    ''
    else if disclosurePolicy == "immediate" then ''
      ## Disclosure Policy

      We follow an immediate disclosure policy. Security issues are addressed and disclosed as quickly as possible:

      1. Confirm the problem and determine affected versions
      2. Prepare fixes for all supported releases
      3. Release patches immediately
      4. Publish security advisory within 24 hours
    ''
    else ''
      ## Disclosure Policy

      When we receive a security bug report, we will:

      1. Confirm the problem and determine affected versions
      2. Audit code to find similar problems
      3. Prepare fixes for all supported releases
      4. Release patches as soon as possible
    '';

in
{
  files = {
    "SECURITY.md" = ''
      # Security Policy

      ## Supported Versions

      We release patches for security vulnerabilities in the following versions:

      | Version | Supported          |
      | ------- | ------------------ |
      ${versionTable}

      ## Reporting a Vulnerability

      If you discover a security vulnerability within this project, please send an email to **${orgEmail}**. All security vulnerabilities will be ${responseTime} addressed.

      **Please do not open public issues for security vulnerabilities.**

      ### What to Include

      When reporting a vulnerability, please include:

      - Description of the vulnerability
      - Steps to reproduce the issue
      - Affected versions (if known)
      - Potential impact assessment
      - Any suggested mitigations

      ${disclosurePolicyText}

      ## Security Best Practices

      Users of this project should:

      - Keep dependencies up to date
      - Monitor security advisories for this repository
      - Follow the principle of least privilege
      - Report suspected vulnerabilities promptly

      ## Comments on this Policy

      If you have suggestions on how this process could be improved, please submit a pull request or contact ${orgEmail}.

      ---
      *This security policy was generated by NixLine. Last updated: ${builtins.toString (builtins.currentTime)}*
    '';
  };

  checks = [
    {
      name = "security-contact-valid";
      check = ''
        if [[ -f SECURITY.md ]]; then
          echo "Checking security contact email format..."
          if ! grep -q '@' SECURITY.md; then
            echo "Error: SECURITY.md appears to be missing a valid email address"
            exit 1
          fi
          echo "Security contact check passed"
        fi
      '';
    }
  ];
}