{ pkgs }:

pkgs.writeShellApplication {
  name = "list-licenses";

  text = ''
    echo "NixLine License Pack - Supported License Types"
    echo "=============================================="
    echo ""
    echo "SPDX License Identifiers (fetched from source):"
    echo "  Apache-2.0    - Apache License 2.0"
    echo "  MIT           - MIT License"
    echo "  GPL-2.0       - GNU General Public License v2.0"
    echo "  GPL-3.0       - GNU General Public License v3.0"
    echo "  LGPL-2.1      - GNU Lesser General Public License v2.1"
    echo "  LGPL-3.0      - GNU Lesser General Public License v3.0"
    echo "  BSD-2-Clause  - BSD 2-Clause 'Simplified' License"
    echo "  BSD-3-Clause  - BSD 3-Clause 'New' or 'Revised' License"
    echo "  ISC           - ISC License"
    echo "  MPL-2.0       - Mozilla Public License 2.0"
    echo "  CC0-1.0       - Creative Commons Zero v1.0 Universal"
    echo "  Unlicense     - The Unlicense"
    echo "  AGPL-3.0      - GNU Affero General Public License v3.0"
    echo "  EPL-2.0       - Eclipse Public License 2.0"
    echo "  EUPL-1.2      - European Union Public License 1.2"
    echo ""
    echo "Configuration examples:"
    echo ""
    echo "# Use SPDX license (fetched from source)"
    echo "[packs.license]"
    echo "type = \"MIT\""
    echo "holder = \"My Organization\""
    echo "year = \"2024\""
    echo ""
    echo "# Use custom license file"
    echo "[packs.license]"
    echo "type = \"Custom\""
    echo "custom_license_file = \"./custom-license.txt\""
    echo "holder = \"My Organization\""
    echo "year = \"2024\""
    echo ""
    echo "# Disable SPDX fetching (use hardcoded fallbacks)"
    echo "[packs.license]"
    echo "type = \"Apache-2.0\""
    echo "fetch_from_source = false"
    echo "holder = \"My Organization\""
    echo "year = \"2024\""
    echo ""
    echo "For more license types, see: https://spdx.org/licenses/"
  '';
}