#
# Promote to Stable Workflow
#
# Updates the stable tag to promote commits from main. Supports two modes:
# 1. PR-based: Triggered when promotion PRs with 'promote-to-stable' label are merged
# 2. Manual: Triggered via workflow_dispatch to promote any commit directly
#
# Uses the reusable nixline-promote-to-stable workflow from .github repo
#

name: Promote to Stable

on:
  pull_request:
    types: [closed]
    branches:
      - main
  workflow_dispatch:
    inputs:
      commit_hash:
        description: 'Commit hash to promote (defaults to HEAD of main)'
        required: false
        type: string

permissions:
  contents: write
  actions: write
  issues: write

jobs:
  promote-pr:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'promote-to-stable')
    uses: NixLine-org/.github/.github/workflows/nixline-promote-to-stable.yml@stable
    with:
      promotion_mode: pr-based
      stable_tag: stable

  promote-manual:
    if: github.event_name == 'workflow_dispatch'
    uses: NixLine-org/.github/.github/workflows/nixline-promote-to-stable.yml@stable
    with:
      promotion_mode: manual
      commit_hash: ${{ github.event.inputs.commit_hash }}
      stable_tag: stable
